import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useEffect, useContext, useState } from 'react'

import app from "../firebase"
import {collection,doc,setDoc,getDocs,getFirestore,addDoc, getDoc,query,where,orderBy, serverTimestamp, or} from "firebase/firestore"
import { async } from '@firebase/util'
import { onSnapshot } from 'firebase/firestore'
//import { getAuth, onAuthStateChanged ,createUserWithEmailAndPassword,GoogleAuthProvider,signInWithPopup} from "firebase/auth";
import { getStorage ,ref,uploadBytes,getDownloadURL} from "firebase/storage";
import React from 'react';
import Script from 'next/script'

import { makeStyles } from '@mui/styles'
import { Typography, Grid, Box } from '@mui/material';
import { AccountBalanceWallet, Chat, Star, Group, PersonAdd, Person } from '@mui/icons-material';
import { getAuth} from "firebase/auth";
import { useRouter } from 'next/router'
import { getDatabase} from 'firebase/database'
import { UserContext } from '../context/context'

export default function UserDashBoard() {
  const [user, setUser] = useState(null);
 const router=useRouter()
 const realtimedb = getDatabase(app)
 const db=getFirestore(app)
 async function getUser(){
    const auth = getAuth();
    let uid;
    if (user) {
      uid=user.uid
      setUser(user)
      const msgRef = collection(db, "messages");
      //get all messages where user is sender or recipient with distinct project id and get all projectids to fetch project details
      //const q = query(msgRef, sel);
    //  const querySnapshot = await getDocs(q);

      
    } else {
      console.log("No user found")
    }
 }
  useEffect(()=>{
    if (user) {
      getUser()
    }else{
      router.push({pathname:'/useregister'})
    }
   } ,[user])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
     
   
   
    </>
  )
}
