import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'

import app from "../firebase"
import {collection,doc,setDoc,getDocs,getFirestore,addDoc, getDoc,query,where,orderBy, serverTimestamp} from "firebase/firestore"
import { async } from '@firebase/util'
import { onSnapshot } from 'firebase/firestore'
//import { getAuth, onAuthStateChanged ,createUserWithEmailAndPassword,GoogleAuthProvider,signInWithPopup} from "firebase/auth";
import { getStorage ,ref,uploadBytes,getDownloadURL} from "firebase/storage";
import React from 'react';
import Script from 'next/script'
import { useRouter } from 'next/router'

export default function AllProposals({clientId,proposals,projectname}) {
 const router=useRouter()
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
     <h1> All Proposals for project {projectname}</h1>
    
    </>
  )
}
export async function getServerSideProps({ query}) {
  const clientId = query.clientId;
  const proid=query.proid;
  const projectname=query.projectname
   const db=getFirestore(app);
  // const docRef=collection(db,"AllProjects")
   const allproposals=collection(db,"Proposals");
 
   let proposals=[]
 
   const propsnapshot=await getDocs(allproposals)
   propsnapshot.forEach((item)=>{
    
    if(item.data().projectid===proid){
   
    proposals.push({id:item.id,data:item.data()})
      
    }
   })



    return {
props: {
       clientId,
    proposals:proposals,
    projectname:projectname
     }
   }
  }