import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import {  useState ,useEffect} from 'react'
import styles from '@/styles/Home.module.css'
import app from "../firebase"
import {collection,doc,setDoc,getDocs,getFirestore,addDoc} from "firebase/firestore"
import { async } from '@firebase/util'
import { getAuth, onAuthStateChanged ,createUserWithEmailAndPassword,GoogleAuthProvider,signInWithPopup,signInWithEmailAndPassword} from "firebase/auth";
import { useRouter } from 'next/router'
import React from 'react';
import  AccountBox  from '@mui/icons-material/AccountBox'
import { PersonAdd } from '@mui/icons-material'
import ListSubheader from '@mui/material/ListSubheader'
import ListIcon from '@mui/icons-material/List';
import Drawer from '@mui/material/Drawer';
import Box from '@mui/material/Box';
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemIcon from '@mui/material/ListItemIcon';
import ListItemText from '@mui/material/ListItemText';
import Divider from '@mui/material/Divider';
import Avatar from '@mui/material/Avatar';
import DashboardIcon from '@mui/icons-material/Dashboard';
import SettingsIcon from '@mui/icons-material/Settings';

import Link from 'next/link'
import Script from 'next/script'


export default function Home({arrayofprojects}) {
   const [isSignup,setSignUp]=useState(false);
   const [isOpen,setOpen]=useState(false);
    const router=useRouter()
    const [button,setButton]=useState('signup')
    const [id,setId]=useState('')
    const [searchQuery, setSearchQuery] = useState('');
    const [isDrawerOpen, setIsDrawerOpen] = React.useState(false);
    const [filteredProjects, setFilteredProjects] = useState([]);

    useEffect(() => {
      if (searchQuery.trim() === '') {
        setFilteredProjects(arrayofprojects);
      } else {
        const filtered = arrayofprojects.filter((project) =>
          project.data.Title.toLowerCase().includes(searchQuery.toLowerCase()) ||
          project.data.Category.toLowerCase().includes(searchQuery.toLowerCase())
        );
        setFilteredProjects(filtered);
      }
    }, [searchQuery, arrayofprojects]);
    const handleToggleDrawer = () => {
      setIsDrawerOpen(!isDrawerOpen);
    };
  

    const handleInputChange = (event) => {
      setSearchQuery(event.target.value);
    }
  
    const handleSearch = (event) => {
      event.preventDefault();
      console.log(`Search Query: ${searchQuery}`);
      // Perform search logic here
    }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Script type="application/javascript" crossorigin="anonymous" src="https://securegw.paytm.in/merchantpgpui/checkoutjs/merchants/{MID}.js"></Script>
      </Head>
      
      <div style={{}}>
        
  
    <div style={{ display: 'flex', justifyContent: 'center', padding: '16px', gap: '16px', alignItems: 'center', backgroundColor: '#fff', boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)', borderRadius: '8px' }}>
  <ListIcon
    sx={{
      width: '32px',
      height: '32px',
      '&:hover': {
        cursor: 'pointer',
      },
      color: '#007bff'
    }}
    onClick={handleToggleDrawer}
  />
  <input
    type="text"
    placeholder="Search..."
    value={searchQuery}
    onChange={handleInputChange}
    style={{
      padding: '8px',
      borderRadius: '4px',
      border: 'none',
      width: '100%',
      height: '40px',
      boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
      outline: 'none',
      backgroundColor: '#f8f8f8',
      color: '#333',
      fontSize: '16px',
      fontFamily: 'inherit'
    }}
  />
  <button onClick={handleSearch} style={{
    padding: '12px 24px',
    borderRadius: '4px',
    backgroundColor: '#007bff',
    color: '#fff',
    border: 'none',
    cursor: 'pointer',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    fontSize: '16px',
    fontFamily: 'inherit',
    fontWeight: 'bold'
  }}>Search</button>
  <NavigationDrawer isOpen={isDrawerOpen} onClose={handleToggleDrawer} />
</div>


      <h3 style={{textAlign:'center'}}>All Projects that are available currently</h3>
     {filteredProjects.map((item)=>{
      return(
      <div style={{ 
        border: '1px solid #ccc',
        borderRadius: '5px',
        padding: '10px',
        maxWidth: '200px',
        margin: '0 auto',
        textAlign:'center'
      }}>
        <h2 style={{ fontSize: '24px' }}>{item.data.Title}</h2><br/>
        {/* <p>{item.data.Des}</p> */}
        <Skills skills={item.data.Skills}/>
        <p>{item.data.uploadedBy}</p>
        <p>{item.data.Category}</p>
        <p>{item.data.Subcategory}</p>
        <h1 style={{color:'green'}}>rs.{item.data.Budget}</h1>
       <button style={{ 
          background: '#0070f3',
          color: 'white',
          padding: '10px',
          borderRadius: '5px',
          border: 'none',
          cursor: 'pointer',
          marginTop: '10px',
          fontWeight: 'bold',
          fontSize: '16px'
        }}  onClick={()=>{
          
            router.push({pathname:'/projectdetails',query:{proid:item.id,clientid:item.data.uid}})
          
        }}>Apply</button>
        </div>
      )
  
     })}
     <RegisterPopup isOpen={isOpen} setSignUp={setSignUp} isSignup={isSignup} setOpen={setOpen} button={button} setButton={setButton} setId={setId}/>

      </div>
    </>
  )
}
const RegisterPopup = ({ isOpen, onClose ,isSignup,setSignUp,setOpen,button,setButton,setId}) => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [r,setR]=useState('reg')
  const db=getFirestore(app)
  const provider = new GoogleAuthProvider();
  const auth = getAuth();
  // const handleSubmitSignUp = (event) => {
  //   event.preventDefault();

  //   // TODO: Add code to register the student with the provided details
  //   console.log('Name:', name);
  //   console.log('Email:', email);
  //   console.log('Password:', password);
   
  //  const docRef=collection(db,"Users");
  //  addDoc(docRef,{
  //   name:name,
  //   email:email,
  //   password:password
  //  }).then((res)=>{
  //   alert("Registration successful");
  //   setSignUp(true)
  //   setOpen(false)
  //  }).catch((err)=>{
  //   alert("Can not register some error occurred");
  //  })
    
    
  // };
  const handleLogin=(event)=>{
   
  const auth = getAuth();
  signInWithPopup(auth, provider)
    .then((result) => {
      const credential = GoogleAuthProvider.credentialFromResult(result);
      const token = credential.accessToken;
      const user = result.user;
    const docRef=doc(db,"Users",user.uid);
    setDoc(docRef,{
    name:user.displayName,
    email:user.email,
    uid:user.uid,
    pic:user.photoURL
   }).then((res)=>{
     console.log(res)
    setSignUp(true)
    setOpen(false)
    setButton('apply')
    setId(user.uid)
   }).catch((err)=>{
    console.log(err)
   })
     
    }).catch((error) => {
      
      const errorCode = error.code;
      const errorMessage = error.message;
     
      const credential = GoogleAuthProvider.credentialFromError(error);
      
    });


  }
  const handleSingUpWithEmail=(event)=>{
    event.preventDefault();
    createUserWithEmailAndPassword(auth, email, password)
  .then((userCredential) => {
    // Signed in 
    const user = userCredential.user;
    // ...
   
    const docRef=doc(db,"Users",user.uid);
    setDoc(docRef,{
     name:name,
     email:user.email,
     uid:user.uid,
     pic:user.photoURL
    }).then((res)=>{
     console.log(res)
     setSignUp(true)
     setOpen(false)
     setButton('apply')
      setId(res.uid)
    }).catch((err)=>{
     console.log(err)
    })

  })
  .catch((error) => {
    const errorCode = error.code;
    const errorMessage = error.message;
    alert(errorMessage);
    // ..
  });
  }
  const handleLoginWithEmail=(event)=>{
event.preventDefault()
const auth = getAuth();
signInWithEmailAndPassword(auth, email, password)
  .then((userCredential) => {
    // Signed in 
    const user = userCredential.user;
    // ...
    setSignUp(true)
    setOpen(false)
    setButton('apply')
    setId(user.uid)

  })
  .catch((error) => {
    const errorCode = error.code;
    const errorMessage = error.message;
    alert(errorMessage)
  });
  }

  if (!isOpen) {
    return null;
  }

  return (
    <div style={{ 
      position: 'fixed',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center'
    }}>
     
     <div  style={{ 
  backgroundColor: '#F8F9FA',
  padding:'40px',
  borderRadius: '5px',
  width: '300px',
  boxShadow: '0px 0px 10px rgba(0, 0, 0, 0.1)'
}}>
  
        <h2 style={{ 
    fontSize: '24px',
    marginBottom: '20px',
    textAlign: 'center',
    color: '#343A40',
    textTransform: 'uppercase'
  }}>Register Student</h2>
        <form onSubmit={handleSingUpWithEmail}>
           <div style={{ marginBottom: '10px' }}>
            <label htmlFor="name"style={{ 
        marginRight: '10px',
        display: 'block',
        color: '#343A40',
        fontSize: '16px'
      }}>Name:</label>
            <input type="text" id="name" value={name} onChange={(e) => setName(e.target.value)}  style={{ 
        width: '100%',
        padding: '10px',
        border: '1px solid #ced4da',
        borderRadius: '5px'
      }}/>
          </div> 
          <div style={{ marginBottom: '10px' }}>
            <label htmlFor="email" style={{ 
        marginRight: '10px',
        display: 'block',
        color: '#343A40',
        fontSize: '16px'
      }}>Email:</label>
            <input type="email" id="email" value={email} onChange={(e) => setEmail(e.target.value)} style={{ 
        width: '100%',
        padding: '10px',
        border: '1px solid #ced4da',
        borderRadius: '5px'
      }} />
          </div>
          <div style={{ marginBottom: '20px' }}>
            <label htmlFor="password" style={{ 
        marginRight: '10px',
        display: 'block',
        color: '#343A40',
        fontSize: '16px'
      }}>Password:</label>
            <input type="password" id="password" value={password} onChange={(e) => setPassword(e.target.value)} style={{ 
        width: '100%',
        padding: '10px',
        border: '1px solid #ced4da',
        borderRadius: '5px'
      }} />
          </div>
          <button type="submit" style={{ 
      background: '#0070f3',
      color: 'white',
      padding: '10px 20px',
      borderRadius: '5px',
      border: 'none',
      cursor: 'pointer',
      fontWeight: 'bold',
      fontSize: '16px',
      display: 'block',
      margin: '0 auto',
      width: '100%',
      maxWidth: '200px',
      textTransform: 'uppercase'
    }} >Register</button>


        </form>
        <h2 style={{ 
    fontSize: '24px',
    marginBottom: '20px',
    textAlign: 'center',
    color: '#343A40',
    textTransform: 'uppercase'
  }}>Login</h2>
        <form onSubmit={handleLoginWithEmail}>
           <div style={{ marginBottom: '10px' }}>
          </div> 
          <div style={{ marginBottom: '10px' }}>
            <label htmlFor="email" style={{ 
        marginRight: '10px',
        display: 'block',
        color: '#343A40',
        fontSize: '16px'
      }}>Email:</label>
            <input type="email" id="email" value={email} onChange={(e) => setEmail(e.target.value)} style={{ 
        width: '100%',
        padding: '10px',
        border: '1px solid #ced4da',
        borderRadius: '5px'
      }} />
          </div>
          <div style={{ marginBottom: '20px' }}>
            <label htmlFor="password" style={{ 
        marginRight: '10px',
        display: 'block',
        color: '#343A40',
        fontSize: '16px'
      }}>Password:</label>
            <input type="password" id="password" value={password} onChange={(e) => setPassword(e.target.value)} style={{ 
        width: '100%',
        padding: '10px',
        border: '1px solid #ced4da',
        borderRadius: '5px'
      }} />
          </div>
          <button type="submit" style={{ 
      background: '#0070f3',
      color: 'white',
      padding: '10px 20px',
      borderRadius: '5px',
      border: 'none',
      cursor: 'pointer',
      fontWeight: 'bold',
      fontSize: '16px',
      display: 'block',
      margin: '0 auto',
      width: '100%',
      maxWidth: '200px',
      textTransform: 'uppercase'
    }} >Log In</button>
        </form>
        <button onClick={handleLogin} style={{ 
  background: '#fff',
  color: '#333',
  padding: '10px 20px',
  borderRadius: '5px',
  border: '1px solid #ccc',
  cursor: 'pointer',
  marginTop: '10px',
  fontWeight: 'bold',
  fontSize: '16px',
  display: 'block',
  margin: '0 auto',
  width: '100%',
  maxWidth: '200px',
  textTransform: 'uppercase',
  backgroundImage: 'url("https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg")',
  backgroundPosition: 'left center',
  backgroundRepeat: 'no-repeat',
  paddingLeft: '40px',
  backgroundSize: '24px 24px'
}}>Sign in with Google</button>

      </div> 
      {/* <div  style={{ 
  backgroundColor: '#F8F9FA',
  padding: '20px',
  padding:'40px',
  borderRadius: '5px',
  width: '400px',
  boxShadow: '0px 0px 10px rgba(0, 0, 0, 0.1)'
}}>
       
        <button onClick={handleLogin} style={{ 
  background: '#fff',
  color: '#333',
  padding: '10px 20px',
  borderRadius: '5px',
  border: '1px solid #ccc',
  cursor: 'pointer',
  marginTop: '10px',
  fontWeight: 'bold',
  fontSize: '16px',
  display: 'block',
  margin: '0 auto',
  width: '100%',
  maxWidth: '200px',
  textTransform: 'uppercase',
  backgroundImage: 'url("https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/google.svg")',
  backgroundPosition: 'left center',
  backgroundRepeat: 'no-repeat',
  paddingLeft: '40px',
  backgroundSize: '24px 24px'
}}>Sign in with Google</button>

      </div> */}

    

      

    </div>
  );
};
const NavigationDrawer = ({ isOpen, onClose }) => {
  return (
    <Drawer anchor="left" open={isOpen} onClose={onClose}>
      
      <Box sx={{ width: 250 }} role="presentation" onClick={onClose} onKeyDown={onClose}>
        <List>
          <ListItem>
            <Avatar />
          </ListItem>
          <ListItem>
            <ListItemText primary="John Doe" />
          </ListItem>
          <Divider />
          <ListSubheader>Navigation</ListSubheader>
          <ListItem button>
            <ListItemIcon>
              <DashboardIcon />
            </ListItemIcon>
            <ListItemText primary="Dashboard" />
          </ListItem>
          <ListItem button>
            <ListItemIcon>
              <SettingsIcon />
            </ListItemIcon>
            <ListItemText primary="Settings" />
          </ListItem>
          <Divider />
          <ListSubheader>Account</ListSubheader>
          <ListItem button>
            <ListItemIcon>
              <AccountBox/>
            </ListItemIcon>
            {/* <ListItemText primary="Sign in/Sing Up"   /> */}
          <Link href='/clientregister'>Client Sign In</Link>
          </ListItem>
          <ListItem button>
            <ListItemIcon>
              <PersonAdd/>
            </ListItemIcon>
            <ListItemText primary="Sign up" />
          </ListItem>
        </List>
      </Box>
    </Drawer>
  );
};
const Skills = ({ skills }) => {
  return (
    <div>
      {skills.split(",").map((skill) => (
        <span
          key={skill}
          style={{
            display: "inline-block",
            background: "#ccc",
            color: "#fff",
            padding: "0.2rem 0.5rem",
            margin: "0.2rem",
            borderRadius: "5px",
          }}
        >
          {skill}
        </span>
      ))}
    </div>
  );
};

export async function getServerSideProps(context) {
  let arrayofprojects=[]
 const db= getFirestore(app);
 const ref=collection(db,"AllProjects");
 const docRef= await getDocs(ref);
 docRef.forEach((doc) => { 
  // console.log(`${doc.id} => ${JSON.stringify(doc.data())}`); 
  arrayofprojects.push({id:doc.id ,data:doc.data()})
});
console.log(arrayofprojects)
  return {
    props: {
      arrayofprojects 
    },
  };
}