import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import {  useState ,useEffect, ReactElement} from 'react'
import app from "../firebase"
import {collection,doc,setDoc,getDocs,getFirestore,addDoc,getDoc, DocumentData} from "firebase/firestore"
import { async } from '@firebase/util'
import { getAuth, onAuthStateChanged ,createUserWithEmailAndPassword,GoogleAuthProvider,signInWithPopup,signInWithEmailAndPassword, OAuthCredential} from "firebase/auth";
import { useRouter } from 'next/router'
import React from 'react';
import Page from 'next';
import  AccountBox  from '@mui/icons-material/AccountBox'
import ListSubheader from '@mui/material/ListSubheader'
import ListIcon from '@mui/icons-material/List';
import NavigationDrawer from '../components/navigation'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Filter from '../components/filter'
import Script from 'next/script'
import Card from '../components/projectcard'
import DarkModeLayout from '../components/layout'
import {useSelector,useDispatch} from 'react-redux';
import Sidebar from '../components/sidebar'
import { ArrowCircleLeftRounded, Filter1, FilterAlt } from '@mui/icons-material'


export default function Home({ arrayofprojects, user }: { arrayofprojects: { id: any, data: any }[], user: any }): ReactElement<any, any> {
  const [isSignup, setSignUp] = useState(false);
    const [isOpen,setOpen]=useState(false);
    const router=useRouter()
    const [button,setButton]=useState('signup')
    const [id,setId]=useState('')
    const [mincost,setminCost]=useState(0)
    const [maxcost,setmaxCost]=useState(0)
    const [searchQuery, setSearchQuery] = useState('');
    const [isLoggin,setIsLoggedin]=useState(false)
    const [categories,setCategories]=useState([])
    const [selectedCategories,setSelectedCategories]=useState([])
    const [isDrawerOpen, setIsDrawerOpen] = React.useState(false);
    const [filteredProjects, setFilteredProjects] = useState([]);
    const [show, setShow] = useState(true);
    const loggedin = useSelector((state:any)=>state.login)
    console.log(loggedin)
   const retriveCategories = ():void=>{
    let catarr:string[]=[]
    arrayofprojects.map((item)=>{
      if(!catarr.includes(item.data.Category)){
        catarr.push(item.data.Category)
      }
    })
    setCategories(catarr)
   }

    useEffect(() => {
      retriveCategories()
      if (searchQuery.trim() === '') {
        if(mincost===0 && maxcost===0 && selectedCategories.length===0){
       
          setFilteredProjects(arrayofprojects);
        }else{
          const filtered = arrayofprojects.filter((project) =>
          (project.data.Budget >= mincost && project.data.Budget <= maxcost) ||
          (selectedCategories.includes(project.data.Category))
        );  
        setFilteredProjects(filtered);
        }
      } else {
      
        const filtered = arrayofprojects.filter((project) =>
          project.data.Title.toLowerCase().includes(searchQuery.toLowerCase()) ||
          project.data.Category.toLowerCase().includes(searchQuery.toLowerCase()) 
        );
        console.log(filtered);
        setFilteredProjects(filtered);
      }
    }, [searchQuery, arrayofprojects, mincost, maxcost,selectedCategories]);


    const handleToggleDrawer = () => {
      setIsDrawerOpen(!isDrawerOpen);
    };
  

    const handleInputChange = (event):void => {
      setSearchQuery(event.target.value);
    }
  
    const handleSearch = (event) => {
      event.preventDefault();
      console.log(`Search Query: ${searchQuery}`);
      // Perform search logic here
    }
  
  return (
    <>
      <Head>
        <title>BuildMyProject</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <div className='flex gap-5'>
   <div className="lg:w-auto hidden lg:block lg:h-auto">
        
        <Sidebar
          isLoggin={isLoggin}
          uid={user}
          login={loggedin}
        />
         
    </div>

        <div className='w-full'>
        <div className=" flex p-4 ">
        <div className=" flex items-start pt-5 lg:hidden ">
          <ListIcon
            className="w-8 h-8 cursor-pointer text-violet-600"
            onClick={handleToggleDrawer}
          />
        </div>
        
      <div className="flex sm:w-full justify-center lg:justify-end lg:items-center gap-2 pt-3 px-2">
        <input
          type="text"
          placeholder="Search..."
          value={searchQuery}
          onChange={handleInputChange}
          className="lg:w-96 sm:w-36 p-2 rounded-md border-none shadow-sm bg-gray-800 focus:bg-gray-500 text-white text-base focus:outline-none"
        />
        <button
          onClick={handleSearch}
          className="px-4 py-2 rounded-md bg-violet-600 hover:bg-violet-700 text-white font-bold transition-colors"
        >
          Search
        </button>
        <NavigationDrawer
          isOpen={isDrawerOpen}
          onClose={handleToggleDrawer}
          isLoggin={isLoggin}
          uid={user}
          login={loggedin}
        />
      </div>

      
    </div>
    <div className="mx-auto lg:h-screen sm:min-h-screen ">
    <div className="lg:flex lg:flex-col  mt-10 gap-8 w-full px-4">
      <div className="flex flex-col w-full px-4">

        <button className='w-44 bg-violet-600 text-white text-md lg:text-xl font-semibold rounded-md py-1 lg:py-4 hover:bg-violet-800 duration-300 ' onClick={()=>setShow(!show)}><span>{show?"Hide":"Show"}</span> Filter <FilterAlt/></button>
        { show? <div className='w-1/2 lg:w-1/3 mt-5'>
          <Filter
            mincost={mincost}
            maxcost={maxcost}
            setMax={setmaxCost}
            setMin={setminCost}
            categories={categories}
            selectedCategories={selectedCategories}
            setSelectedCategories={setSelectedCategories}
          />
        </div> : null}
      </div>
          

        <div className="sm:col-span-3 lg:w-full">
          {filteredProjects.map((item) => (
            <Card key={item.id} item={item} user={user} />
          ))}
        </div>
      </div>
    </div>
        </div>
   </div>
      
    </>
  )
}



export async function getServerSideProps(context:any):Promise<any> {
  let arrayofprojects: { id: any, data: any }[] = [];
  const {uid}=context.query
  const db = getFirestore(app);
  let user:DocumentData | null = null;
  if(uid){
    const userDocRef = doc(db, 'Users', uid);
    const userDocSnapshot = await getDoc(userDocRef);
     user = userDocSnapshot.data();
  }
 
 const ref=collection(db,"AllProjects");
 const docRef= await getDocs(ref);
 docRef.forEach((doc:DocumentData) => { 
  let id:any=doc.id;
  let data:any=doc.data()
  arrayofprojects.push({id:id ,data:data})
});

  return {
    props: {
      arrayofprojects ,
      user:user?user:'none',
    },
  };
}