import Head from 'next/head'
import Image from 'next/image'
import { getFirestore, doc, getDoc } from 'firebase/firestore'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'
import app from '../firebase'
export default function ProjectDetails({ project }) {
  const router = useRouter()

  if (router.isFallback) {
    return <div>Loading...</div>
  }

  return (
    <>
      <Head>
        <title>{project.Title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ 
  maxWidth: '500px',
  margin: '0 auto',
  padding: '20px',
  border: '1px solid #ccc',
  borderRadius: '5px',
  boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
}}>
  <h1 style={{ 
    fontSize: '28px',
    fontWeight: 'bold',
    marginBottom: '10px',
  }}>{project.Title}</h1>
  <p style={{ 
    fontSize: '16px',
    lineHeight: '1.5',
    marginBottom: '20px',
  }}>{project.Des}</p>
  <div style={{ 
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '20px',
  }}>
    <p style={{ fontSize: '18px', fontWeight: 'bold' }}>Category: {project.Category}</p>
    <p style={{ fontSize: '18px', fontWeight: 'bold' }}>Subcategory: {project.Subcategory}</p>
  </div>
  <p style={{ 
    fontSize: '18px',
    fontWeight: 'bold',
    marginBottom: '20px',
  }}>Budget: rs.{project.Budget}</p>
  <div style={{ 
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: '20px',
  }}>
    <p style={{ 
      fontSize: '18px',
      fontWeight: 'bold',
      marginRight: '10px',
    }}>Skills:</p>
     <div>
      {project.Skills.split(",").map((skill) => (
        <span
          key={skill}
          style={{
            display: "inline-block",
            background: "#ccc",
            color: "#fff",
            padding: "0.2rem 0.5rem",
            margin: "0.2rem",
            borderRadius: "5px",
          }}
        >
          {skill}
        </span>
      ))}
    </div>
  </div>
  <p style={{ 
    fontSize: '18px',
    fontWeight: 'bold',
    marginBottom: '20px',
  }}>Posted by: {project.uploadedBy}</p>
  <button style={{ 
    backgroundColor: '#0070f3',
    color: '#fff',
    padding: '10px',
    borderRadius: '5px',
    border: 'none',
    cursor: 'pointer',
    fontWeight: 'bold',
    fontSize: '18px',
  }}>Apply</button>
</div>

    </>
  )
}

export async function getServerSideProps(context) {
  const { proid } = context.query
  const db = getFirestore(app)
  const projectDoc = doc(db, 'AllProjects', proid)
  const projectData = await getDoc(projectDoc)
  const project = projectData.data()

  return {
    props: {
      project,
    },
  }
}