import Head from 'next/head'
import { use, useEffect, useState,useContext } from 'react'
import app from "../firebase"
import { getStorage ,ref,uploadBytes,getDownloadURL} from "firebase/storage";
import React from 'react'
import { getFirestore, collection, getDocs, addDoc,doc, setDoc, getDoc, query, where, orderBy, limit } from 'firebase/firestore';
import { getAuth, onAuthStateChanged,setPersistence,browserLocalPersistence ,createUserWithEmailAndPassword,GoogleAuthProvider,signInWithPopup,signInWithEmailAndPassword} from "firebase/auth";
import { useRouter } from 'next/router'
import { UserContext } from '../context/context';
export default function UserDashBoard() {
const router=useRouter()
const db=getFirestore(app)

const [user, setUser] = useState({name:'',email:'',uid:''});
const usera = useContext(UserContext) 

async function getUser(){
  const auth = getAuth();
  console.log(usera)
  let uid;
  if (usera) {
    uid=usera.uid
    const docRef = doc(db, "Users", uid);
    const docSnap = await getDoc(docRef);
    if (docSnap.exists()) {
      setUser(docSnap.data() as { name: string; email: string; uid: string; })
    } else {
      console.log("No such document!");
    }
  } else {
    console.log("No user found")
  }

}

useEffect(()=>{
  if (usera) {
    getUser()
  }
},[usera])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
     
    <div className="flex wrap bg-blue" style={{display:'flex',flexWrap:'wrap',justifyContent:'center',gap:'20px'}}>
      <h2>Welcome {user.name} </h2>
<div style={{background:'#e6e6e6',padding:'100px',borderRadius:'10px',maxWidth:'300px'}}>Total Earnings</div>
<div style={{background:'#e6e6e6',padding:'100px',borderRadius:'10px'}}  onClick={()=>{router.push({pathname:'/allapplication',query:{Userid:user.uid}})}}    >All Applications</div>
<div style={{background:'#e6e6e6',padding:'100px',borderRadius:'10px'}} >Saved Projects</div>
<div style={{background:'#e6e6e6',padding:'100px',borderRadius:'10px'}}>Apply as Mentor</div>
<div style={{background:'#e6e6e6',padding:'100px',borderRadius:'10px'}}
onClick={()=>{
  router.push({pathname:'/'})
}}
>Apply for more Projects</div>
<div  style={{background:'#e6e6e6',padding:'100px',borderRadius:'10px'}}>Get a Mentor for Projects</div>
    </div> 
   
    </>
  )
}
