import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useEffect, useParams, useState } from 'react'

import app from "../firebase"
import {collection,doc,setDoc,getDocs,getFirestore,addDoc, getDoc,query,where,orderBy, serverTimestamp} from "firebase/firestore"
import { async } from '@firebase/util'
import { onSnapshot } from 'firebase/firestore'
//import { getAuth, onAuthStateChanged ,createUserWithEmailAndPassword,GoogleAuthProvider,signInWithPopup} from "firebase/auth";
import { getStorage ,ref,uploadBytes,getDownloadURL} from "firebase/storage";
import React from 'react';
import Script from 'next/script'

import { makeStyles } from '@mui/styles'
import { Typography, Grid, Box } from '@mui/material';
import { AccountBalanceWallet, Chat, Star, Group, PersonAdd, Person } from '@mui/icons-material';
import { getAuth, onAuthStateChanged,setPersistence,browserLocalPersistence ,createUserWithEmailAndPassword,GoogleAuthProvider,signInWithPopup,signInWithEmailAndPassword} from "firebase/auth";
import { useRouter } from 'next/router'


export default function UserDashBoard({user}) {
 // const [user, setUser] = useState(null);
const router=useRouter()
 const db=getFirestore(app)

// useEffect(() => {
//   const auth = getAuth();
//   const unsubscribe = onAuthStateChanged(auth, (user) => {
//     if (user) {
//       setUser({
//         displayName: user.displayName,
//         email: user.email,
//         photoURL: user.photoURL,
//         uid: user.uid,
//       });
//     } else {
//       setUser(null);
//     }
//   });

//   return unsubscribe;
// }, []);
// console.log(user)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
     
    <div className="flex wrap bg-blue" style={{display:'flex',flexWrap:'wrap',justifyContent:'center',gap:'20px'}}>
      <h2>Welcome {user.name} </h2>
<div style={{background:'#e6e6e6',padding:'100px',borderRadius:'10px',maxWidth:'300px'}}>Total Earnings</div>
<div style={{background:'#e6e6e6',padding:'100px',borderRadius:'10px'}}  onClick={()=>{router.push({pathname:'/allchats',query:{Userid:user.uid}})}}    >All Chats</div>
<div style={{background:'#e6e6e6',padding:'100px',borderRadius:'10px'}} >Saved Projects</div>
<div style={{background:'#e6e6e6',padding:'100px',borderRadius:'10px'}}>Apply as Mentor</div>
<div style={{background:'#e6e6e6',padding:'100px',borderRadius:'10px'}}
onClick={()=>{
  router.push({pathname:'/',query:{uid:user.uid}})
}}
>Apply for more Projects</div>
<div  style={{background:'#e6e6e6',padding:'100px',borderRadius:'10px'}}>Get a Mentor for Projects</div>
    </div> 
   
    </>
  )
}
export async function getServerSideProps(context) {
  const { uid } = context.query;
  const db = getFirestore(app);
  const userDocRef = doc(db, 'Users', uid);
  const userDocSnapshot = await getDoc(userDocRef);
  const user = userDocSnapshot.data();

  return {
    props: {
      user:user?user:'none',
    },
  };
}