import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import app from "../firebase"
import {collection,doc,setDoc,getDocs,getFirestore} from "firebase/firestore"

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      {console.log}
      </div>
    </>
  )
}
export async function getStaticProps(context) {
  let data;
  const db=getFireStore(app)
  const projectRef=collection(db,"AllProjects");
  const docSpanp= getDocs(projectRef).then((res)=>{
    data=res;
  }).catch(err=>console.log(err))
  return {

    props: {data:data}, // will be passed to the page component as props
  }
}
