import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useEffect, useParams, useState } from 'react'

import app from "../firebase"
import {collection,doc,setDoc,getDocs,getFirestore,addDoc, getDoc,query,where,orderBy, serverTimestamp} from "firebase/firestore"
import { async } from '@firebase/util'
import { onSnapshot } from 'firebase/firestore'
//import { getAuth, onAuthStateChanged ,createUserWithEmailAndPassword,GoogleAuthProvider,signInWithPopup} from "firebase/auth";
import { getStorage ,ref,uploadBytes,getDownloadURL} from "firebase/storage";
import React from 'react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import Button from '@mui/material/Button';
import { styled } from '@mui/system';

const StyledButton = styled(Button)({
  color: '#fff',
  backgroundColor: '#007bff',
  '&:hover': {
    backgroundColor: '#0069d9',
  },
});
export default function UserDashBoard() {
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
      <Typography variant="h5" sx={{ mt: 2 }}>
        Total earnings 0rs
      </Typography>
      <Box sx={{ display: 'flex', flexDirection: 'row', justifyContent: 'space-evenly', width: '100%', mt: 4 }}>
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <Typography variant="h6">Projects Completed</Typography>
          <Typography variant="h4">0</Typography>
        </Box>
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <Typography variant="h6">Chat & Proposals</Typography>
          <Typography variant="h4">0</Typography>
        </Box>
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <Typography variant="h6">Apply to more projects</Typography>
          <StyledButton variant="contained">Apply Now</StyledButton>
        </Box>
      </Box>
      <Box sx={{ display: 'flex', flexDirection: 'row', justifyContent: 'space-evenly', width: '100%', mt: 4 }}>
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <Typography variant="h6">Saved Projects</Typography>
          <Typography variant="h4">0</Typography>
        </Box>
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <Typography variant="h6">Apply to become a mentor</Typography>
          <StyledButton variant="contained">Apply Now</StyledButton>
        </Box>
        <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <Typography variant="h6">Settings</Typography>
          <StyledButton variant="contained">Edit</StyledButton>
        </Box>
      </Box>
    </Box>
    </>
  )
}
// export async function getServerSideProps({ query}) {
//   const clientId = query.clienttId;
//   const UserId = query.Userid;
//     return {
//       props: {
//         clientId,
//        UserId
//       }
//     }
//   }